### ISSUE TITLE
Can't run demo

### ISSUE THREAD

**Issue by aprilahijriyan** [quitegreensky/akivymd#16]
After I cloned the akivymd repo.
I got this:

```
Traceback (most recent call last):
   File "kivy\properties.pyx", line 2023, in kivy.properties.ColorProperty.convert
   File "kivy\properties.pyx", line 2041, in kivy.properties.ColorProperty.parse_list
 ValueError: Invalid value for color (got [])

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\lang\builder.py", line 701, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 840, in kivy.properties.ListProperty.set
   File "kivy\properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "c:\users\titiw\projects\kivyapp\kivymd\kivymd\uix\label.py", line 379, in on_text_color
     self.color = self.text_color
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 527, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 2025, in kivy.properties.ColorProperty.convert
 ValueError: MDIcon.color has an invalid format (got [])

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "main.py", line 136, in <module>
     DemoApp().run()
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\base.py", line 387, in idle
     Clock.tick()
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "c:\users\titiw\projects\kivyapp\akivymd\akivymd\uix\rating.py", line 163, in _update
     self._generate_items()
   File "c:\users\titiw\projects\kivyapp\akivymd\akivymd\uix\rating.py", line 168, in _generate_items
     item = _RaitingItem(
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\uix\behaviors\button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\uix\boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\uix\widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "C:\Users\titiw\projects\kivyapp\venv\lib\site-packages\kivy\lang\builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 11:
 ...
       9:        icon: root.icon
      10:        theme_text_color: "Custom"
 >>   11:        text_color : root.text_color
      12:        font_size: root.font_size
      13:        halign: "center"

```

**Comment by quitegreensky** [comment]
Fixed. install again `python -m pip install https://github.com/quitegreensky/akivymd/archive/master.zip`
