### ISSUE TITLE
No module named 'akivymd.uix.progresswidget' error

### ISSUE THREAD

**Issue by ghost** [quitegreensky/akivymd#8]
I just download akivymd demo and the installed using `pip install akivymd`  and no error shows up
and then when I run the demo I get the following error

```
husam@Hussam-Hardware MINGW64 ~/OneDrive/Desktop
$ python main.py
[INFO   ] [Logger      ] Record log in C:\Users\husam\.kivy\logs\kivy_20-10-06_108.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer_dev" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle_dev" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew_dev" 0.2.0
[INFO   ] [Kivy        ] v2.0.0rc3, git-20c14b2, 20200615
[INFO   ] [Kivy        ] Installed at "C:\Users\husam\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\husam\AppData\Local\Programs\Python\Python37\python.exe"
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2020-08-11 (installed at "C:\Users\husam\AppData\Local\Programs\Python\Python37\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 185 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer, img_gif ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 27.20.100.8587'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 27.20.100.8587'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [AKivymd     ] v1.1
 Traceback (most recent call last):
   File "main.py", line 7, in <module>
     from screens import bottomnavigation, spinners, dataloader, selectionlist, piechart,\
   File "C:\Users\husam\OneDrive\Desktop\screens\progresswidget.py", line 3, in <module>
     from akivymd.uix.progresswidget import AKCircularProgress
 ModuleNotFoundError: No module named 'akivymd.uix.progresswidget'

```

**Comment by quitegreensky** [comment]
i think you are using a wrong version to run the demo app. try installing the last changes using  `python -m pip install --force-reinstall https://github.com/quitegreensky/akivymd/archive/master.zip`

**Comment by ghost** [comment]
yes it works thanks 
btw it's very amazing widgets i hope see some doc about how to use them soon
good luck
